deployments_storage_account_name: xtrastrge6o3yq2ito5ta
bosh_storage_account_name: pcfkbboshstorage
azure_storage_access_key: 5Kk7o6Hb7oxRcFdCQY8KpL5ZzbFPVYojBbVaLedR29bRm5LY3OwC3sP61GquL47duEF0NQNhfvdJsIeNrSDuQg==
azure_account: mysqlstrge6o3yq2ito5ta
