resources:
- name: azs-concourse
  type: git
  source: 
    uri: https://github.com/bottkars/azs-concourse
    branch: master
    private_key: ((azs-resource-key.private_key))

- name: az-cli-image
  type: docker-image
  source: 
    repository: microsoft/azure-cli


jobs:
- name: test-azcli 
  plan:
  - get: azs-concourse
  - get: az-cli-image
  - task: test-azcli
    image: az-cli-image
    file: azs-concourse/ci/tasks/test-task.yml

- name: run-azcli
  plan:
  - get: azs-concourse
  - get: az-cli-image
  - task: task2
    image: az-cli-image
    file: azs-concourse/ci/tasks/task2.yml  
    params:
      CA_CERT: ((azs_ca.ca))


