resources:
- name: azs-concourse
  type: git
  source: 
    uri: https://github.com/bottkars/azs-concourse
    branch: master
    private_key: ((azs-resource-key.private_key))

- name: az-cli-image
  type: docker-image
  source: 
    repository: microsoft/azure-cli

- name: cert
  type: git
  source:
    uri: git@github.com:bottkars/platform-automation.git
    private_key: ((plat-auto-pipes-deploy-key.private_key))
    branch: master
jobs:
- name: test-azcli 
  plan:
  - get: azs-concourse
  - get: az-cli-image
  - task: test-azcli
    image: az-cli-image
    file: azs-concourse/ci/tasks/test-task.yml

- name: run-azcli-get-vms
  plan:
  - get: cert
  - get: azs-concourse
  - get: az-cli-image
  - task: get-vms
    image: az-cli-image
    file: azs-concourse/ci/tasks/get-vms.yml  
    input_mapping:
      root_ca: cert
    params:
      CA_CERT: cert/root.pem
      AZURE_TENANT_ID: ((tenant-id))
      AZURE_CLIENT_ID: ((client-id))
      AZURE_CLIENT_SECRET: ((client-secret))
      AZURE_SUBSCRIPTION_ID: ((subscription-id))

