resources:
- name: pas-product
  #icon: amazon-drive
  type: s3
  source:
    access_key_id: ((access_key_id))
    bucket: ((buckets_pivnet_products))
    endpoint:  ((s3_endpoint))
    secret_access_key: ((secret_access_key))
    regexp: pas-product/\[elastic-runtime,(.*)\]cf-.*.pivotal
    
- name: pas-stemcell
  #icon: amazon-drive
  type: s3
  source:
    access_key_id: ((access_key_id))
    bucket: ((buckets_pivnet_products))
    endpoint:  ((s3_endpoint))
    region_name: ((s3_region_name))
    secret_access_key: ((secret_access_key))
    regexp: pas-stemcell/\[stemcells-ubuntu-xenial,(.*)\]bosh-stemcell-.*-azure.*\.tgz

jobs:    


- name: get-pas
  plan:
  - aggregate:
    #- get: daily-trigger
    #  trigger: true
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: config
  - task: credhub-interpolate
    <<: *credhub-interpolate
  - task: download-pas-product-and-stemcell
    image: platform-automation-image
    file: platform-automation-tasks/tasks/download-product.yml
    params:
      CONFIG_FILE: download-product-configs/download-pas.yml
    output_mapping: {downloaded-stemcell: pas-stemcell}
  - aggregate:
    - put: pas-product
      params:
        file: downloaded-product/*.pivotal
    - put: pas-stemcell
      params:
        file: pas-stemcell/*.tgz

- name: upload-and-stage-pas
  serial: true
  plan:
    - aggregate:
        - get: platform-automation-image
          params:
            unpack: true
            passed:
              - export-installation
            trigger: true
        - get: platform-automation-tasks
          params:
            unpack: true
        - get: configuration
        - get: variable
    - task: interpolate-creds
      <<: *interpolate-creds
    - task: download-pas
      image: platform-automation-image
      file: platform-automation-tasks/tasks/download-product-s3.yml
      params:
        CONFIG_FILE: download-product-configs/download-pas.yml
      input_mapping:
        config: interpolated-creds
      output_mapping:
        downloaded-product: pas-product
        downloaded-stemcell: pas-stemcell
    - task: upload-product
      image: platform-automation-image
      file: platform-automation-tasks/tasks/upload-product.yml
      input_mapping:
        product: pas-product
        env: interpolated-creds
      params:
        ENV_FILE: ((foundation))/env/env.yml
    - task: upload-pas-stemcell
      image: platform-automation-image
      file: platform-automation-tasks/tasks/upload-stemcell.yml
      input_mapping:
        env: interpolated-creds
        stemcell: pas-stemcell
      params:
        ENV_FILE: ((foundation))/env/env.yml
    - task: stage-product
      image: platform-automation-image
      file: platform-automation-tasks/tasks/stage-product.yml
      input_mapping:
        product: pas-product
        env: interpolated-creds
      params:
        ENV_FILE: ((foundation))/env/env.yml

