---
s3_env: &s3_env
  access_key_id: ((((foundation))/s3_access_key_id))
  endpoint:  ((((foundation))/s3_endpoint))
  region_name: ((((foundation))/s3_region_name))
  secret_access_key: ((((foundation))/s3_secret_access_key))

resource_types:
- name: rss
  type: docker-image
  source:
    repository: starkandwayne/rss-resource
    tag: latest
- name: twitter
  type: docker-image
  source:
    repository: jghiloni/twitter-concourse-resource

resources:
- name: asdk-release-file
  tags: ((tags))
  icon: cloud-download
  type: s3
  source:
    <<: *s3_env
    bucket: ((buckets_asdk_release))
    regexp: asdk-1.(((asdk.version)).*).yml

- name: tweet
  type: twitter
  icon: twitter
  source:
    consumer_key: ((twitter.ConsumerKey))
    consumer_secret: ((twitter.ConsumerSecret))
    access_token: ((twitter.AccessToken))
    access_token_secret: ((twitter.AccessTokenSecret))   

- name: azurestack-rss
  type: rss
  source:
    url: "https://support.microsoft.com/app/content/api/content/feeds/sap/en-us/32d322a8-acae-202d-e9a9-7371dccf381b/rss"

- name: after-midnight
  type: time
  icon: calendar-clock
  source:
#    start: 01:00 AM
#    stop: ((after_midnight_end))
    interval: 1h
    location: Europe/Berlin 

- name: platform-automation-image
  icon: cloud-download
  type: s3
  source:
    <<: *s3_env
    bucket: ((((foundation))/buckets_pivnet_image))
    regexp: platform-automation-image-(.*).tgz

- name: azs-concourse
  tags: ((tags))
  icon: github
  type: git  
  source: 
    uri: https://github.com/bottkars/azs-concourse.git
    branch: master

jobs:
- name: get-asdk-release
  plan:
  - in_parallel:
    - get: after-midnight
      trigger: true
    - get: platform-automation-image
      tags: ((tags))
      params:
        unpack: true      
    - get: azs-concourse
      tags: ((tags))
  - task: check-asdk-release 
    tags: ((tags))
    image: platform-automation-image
    file: azs-concourse/ci/tasks/check-asdk.yml
    output_mapping:
      asdk-release: asdk-release-file  
    params:
      ASDK_VERSION: ((asdk.version))
      FROM: ((asdk.minor_version))
    on_success:
      try:    
        put: asdk-release-file
        params:
          file: asdk-release-file/asdk-*.yml
        on_success:
          put: tweet
          params:
            media:
            - azs-concourse/media/avatar.jpg
            status: >
              OMG! #AzureStackHub ASDK ((asdk.version)) is now live deployed
              from my custom @concourseci pipeline at labbuildr@home!  

- name: download-asdk
  plan:
  - in_parallel:
    - get: asdk-release-file
      tags: ((tags))
      trigger: true
    - get: platform-automation-image
      tags: ((tags))
      params:
        unpack: true      
    - get: azs-concourse
      tags: ((tags))
#  - put: tweet
#    tags: ((tags))
#    params:
#      media:
#      - azs-concourse/media/avatar.jpg
#      status: >
#        OMG! Apparently, I strongly believe that #AzureStackHub #ASDK ((asdk.version)) 
#        is soon available !! (indicated by my Harddrive LED))
#        from my custom @concourseci pipeline in my Homelab  

  - task: download-asdk-release 
    tags: ((tags))
    image: platform-automation-image
    file: azs-concourse/ci/tasks/download-asdk.yml
    input_mapping:
      asdk: asdk-release-file
    params:
      <<: *s3_env
      bucket: ((buckets_asdk_release))

- name: check-rss    
  plan:
  - get: azurestack-rss
    trigger: true
  - task: alert
    config:
      inputs: 
        - name: azurestack-rss
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: bash
        args:
        - "-c"
        - |
          echo "I cant believe this works"
          ls -lisaR
          printenv


- name: prepare_asdk_files
  plan:
  - get: azs-concourse
  - get: asdk-release-file
  - task: copy_asdk_files_from_s3
    input_mapping:
      asdk-release: asdk-release-file
    params:
      <<: *s3_env
      bucket: ((buckets_asdk_release))
      ASDK_HOST: ((asdk_host))
      ASDK_USERNAME: ((cloudadmin_username))
      ASDK_PASSWORD:  ((cloudadmin_password))
    file: azs-concourse/ci/tasks/copy-asdk-worker-win-from-s3.yml
  - task: copy_asdk_files_to_asdk_host
    params:
      ASDK_HOST: ((asdk_host))
      ASDK_USERNAME: ((cloudadmin_username)))
      ASDK_PASSWORD:  ((cloudadmin_password))
      ASDK_FILE_DESTINATION: "E:\\ASDK"
    file: azs-concourse/ci/tasks/copy-asdk-files-to-asdk-host.yml


- name: create_cloudbuilder
  plan:
  - get: azs-concourse
  - task: dehydrate_cloudbuilder  
    params:
      ASDK_HOST: ((asdk_host))
      ASDK_USERNAME: ((cloudadmin_username))
      ASDK_PASSWORD:  ((cloudadmin_password))
      ASDK_FILE_DESTINATION: "E:\\ASDK"
    file: azs-concourse/ci/tasks/dehydrate_cloudbuilder.yml
  

    