s3_env: &s3_env
  access_key_id: ((((foundation))/s3_access_key_id))
  endpoint:  ((((foundation))/s3_endpoint))
  region_name: ((((foundation))/s3_region_name))
  secret_access_key: ((((foundation))/s3_secret_access_key))


credhub_env: &credhub_env
  CREDHUB_CLIENT: ((((foundation))/credhub-client))
  CREDHUB_SECRET: ((((foundation))/credhub-secret))
  CREDHUB_SERVER: ((((foundation))/credhub-server))
  PREFIX: /concourse/main/((foundation))
  CREDHUB_CA_CERT: ((((foundation))/credhub-ca-cert.certificate))



resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
   

resources:
# triggers
#- name: daily-trigger
#  icon: calendar-clock
#  type: time
#  source:
#    interval: 24h


- name: one-time-trigger
  icon: calendar-clock
  type: time
  source:
    interval: 999999h

#- name: after-midnight
#  type: time
#  source:
#    start: 01:00 AM
#    stop: ((after_midnight_end))
#    interval: 24h
#    location: Europe/Berlin 

#- name: installation
#  icon: cloud-download
#  type: s3
#  source:
#    <<: *s3_env
#    bucket: ((buckets.installation))
#    regexp: ((foundation))/installation-(.*).zip    
#- name: platform-automation-pivnet
#  type: pivnet
#  source:
#    api_token: ((((foundation))/pivnet-token))
#    product_slug: platform-automation
#    product_version: 4\.*\.(.*)
#    sort_by: semver


- name: dps-automation-image
  icon: cloud-download
  type: s3
  source:
    <<: *s3_env
    bucket: ((buckets.pivnet_image))
    regexp: platform-automation-image-(.*).tgz


- name: dps_modules
  tags: ((tags))
  icon: git
  type: git
  check_every: 10m  
  source:  
    uri: https://github.com/bottkars/dps_modules.git
    branch: master

## product resources
- name: ddve
  type: s3
  icon: folder-move
  source:
    <<: *s3_env
    bucket: ((buckets.dps_products))
    regexp: ddve/ddve-(([78])\.([234567]{1,2})\.([0-9]{1,2})\.([0-9]{1,2})-([0-9]{5,6})).ova #only release builds


jobs:
#- name: get-platform-automation
#  plan:
#  - in_parallel:
#    - get: after-midnight
#      trigger: true
#    - get: platform-automation-pivnet
#      trigger: true
#    - put: dps-automation-image
#      params:
#        file: platform-automation-pivnet/*image*.tgz

- name: deploy-ddve-ova
  plan:
  - in_parallel:
    - get: one-time-trigger
      trigger: true
    - get: ddve
      tags: ((tags))
      params:
        unpack: false
    - get: dps-automation-image
      params:
        unpack: true
      tags: ((tags))        
    - get: dps_modules
      tags: ((tags))
  - task: deploy-ova
    tags: ((tags))
    image: dps-automation-image
    file: dps_modules/ci/tasks/deploy-ppdd.yml
    input_mapping:
      dps_modules: dps_modules
      ddve: ddve
    params:
      DEBUG: "TRUE"
      GOVC_INSECURE: ((GOVC.INSECURE))
      GOVC_PASSWORD: ((GOVC.PASSWORD))
      GOVC_URL: ((GOVC.URL))
      GOVC_USERNAME: ((GOVC.USERNAME))
      GOVC_RESOURCE_POOL: ((GOVC.RESOURCE_POOL))
      GOVC_DATASTORE: ((GOVC.DATASTORE)) 
      GOVC_DATACENTER: ((GOVC.DATACENTER)) 
      GOVC_NETWORK: ((GOVC.NETWORK))
      GOVC_VM_IPATH: ((GOVC.DATACENTER))/vm/((DDVE.FOLDER))/((DDVE.VMNAME))
      DDVE_NETWORK: ((DDVE.NETWORK))
      DDVE_ADDRESS: ((DDVE.ADDRESS))
      DDVE_GATEWAY: ((DDVE.GATEWAY))
      DDVE_NETMASK: ((DDVE.NETMASK))
      DDVE_FQDN: ((DDVE.FQDN))
      DDVE_VMNAME: ((DDVE.VMNAME))
      DDVE_DNS: ((DDVE.DNS))
      DDVE_TYPE: ((DDVE.TYPE))    
- name: configure-ppdd
  plan:
  - in_parallel:
    - get: one-time-trigger
      trigger: false
    - get: dps-automation-image
      passed: [ deploy-ddve-ova ]
      params:
        unpack: true
      tags: ((tags))        
    - get: dps_modules
      tags: ((tags))
  - task: configure-ppdd
    tags: ((tags))
    image: dps-automation-image
    file: dps_modules/ci/tasks/configure-ppdd.yml
    input_mapping:
      dps_modules: dps_modules
    params:
      DEBUG: "FALSE"
      GOVC_INSECURE: ((GOVC.INSECURE))
      GOVC_PASSWORD: ((GOVC.PASSWORD))
      GOVC_URL: ((GOVC.URL))
      GOVC_USERNAME: ((GOVC.USERNAME))
      GOVC_RESOURCE_POOL: ((GOVC.RESOURCE_POOL))
      GOVC_DATASTORE: ((GOVC.DATASTORE)) 
      GOVC_DATACENTER: ((GOVC.DATACENTER))       
      DDVE_NETWORK: ((DDVE.NETWORK))
      DDVE_ADDRESS: ((DDVE.ADDRESS))
      DDVE_GATEWAY: ((DDVE.GATEWAY))
      DDVE_NETMASK: ((DDVE.NETMASK))
      DDVE_FQDN: ((DDVE.FQDN))
      DDVE_VMNAME: ((DDVE.VMNAME))
      DDVE_DNS: ((DDVE.DNS))
      DDVE_PASSWORD: ((DDVE.SETUP_PASSWORD))
      DDVE_USERNAME: ((DDVE.USERNAME))
      DDVE_FOLDER: ((DDVE.FOLDER))
      DDVE_INTERFACE: ((DDVE.INTERFACE)) 
      GOVC_VM_IPATH: ((GOVC.DATACENTER))/vm/((DDVE.FOLDER))/((DDVE.VMNAME))
- name: delete-ppdd
  plan:
  - in_parallel:
    - get: dps-automation-image
      params:
        unpack: true
      tags: ((tags))
      passed: [ deploy-ddve-ova ]              
    - get: dps_modules
      tags: ((tags))
  - task: delete-ddve
    tags: ((tags))
    image: dps-automation-image
    file: dps_modules/ci/tasks/delete-ddve.yml
    input_mapping:
      dps_modules: dps_modules
    params:
      DEBUG: "FALSE"
      GOVC_INSECURE: ((GOVC.INSECURE))
      GOVC_PASSWORD: ((GOVC.PASSWORD))
      GOVC_URL: ((GOVC.URL))
      GOVC_USERNAME: ((GOVC.USERNAME))
      GOVC_RESOURCE_POOL: ((GOVC.RESOURCE_POOL))
      GOVC_DATASTORE: ((GOVC.DATASTORE)) 
      GOVC_DATACENTER: ((GOVC.DATACENTER)) 
      GOVC_NETWORK: ((GOVC.NETWORK))
      DDVE_VMNAME: ((DDVE.VMNAME))
