---
s3_env: &s3_env
  access_key_id: ((((foundation))/s3_access_key_id))
  endpoint:  ((((foundation))/s3_endpoint))
  region_name: ((((foundation))/s3_region_name))
  secret_access_key: ((((foundation))/s3_secret_access_key))
azure_env: &azure_env
  PROFILE: ((arm_profile))
  CA_CERT: ((((foundation))/azs_ca.certificate))
  AZURE_CLI_CA_PATH: /opt/az/lib/python3.6/site-packages/certifi/cacert.pem
  ENDPOINT_RESOURCE_MANAGER: ((((foundation))/endpoint-resource-manager)) 
  VAULT_DNS:  ((vault-dns))
  SUFFIX_STORAGE_ENDPOINT: ((suffix-storage-endpoint))
  AZURE_TENANT_ID: ((((foundation))/tenant_id))
  AZURE_CLIENT_ID: ((((foundation))/client_id))
  AZURE_CLIENT_SECRET: ((((foundation))/client_secret))
  AZURE_SUBSCRIPTION_ID: ((((foundation))/subscription_id))
  RESOURCE_GROUP: ((resource_group))
  LOCATION: ((azurestack_region))


credhub_env: &credhub_env
  CREDHUB_CLIENT: ((credhub-client))
  CREDHUB_SECRET: ((credhub-secret))
  CREDHUB_SERVER: ((credhub-server))
  PREFIX: /concourse/main/((foundation))
  CREDHUB_CA_CERT: ((credhub-ca-cert.certificate))

stage_steps: &stage_steps
  steps:
    - get: platform-automation-image
      tags: ((tags))
      params:
        unpack: true
    - get: platform-automation-tasks
      tags: ((tags))
      params:
        unpack: true
    - get: templates
      tags: ((tags))
    - get: variable
      tags: ((tags))

stage_config: &stage_config
  image: platform-automation-image
  file: platform-automation-tasks/tasks/staged-config.yml
  input_mapping:
    env: variable

do_stage_commit: &do_stage_commit
  image: platform-automation-image
  file: platform-automation-tasks/tasks/make-git-commit.yml
  input_mapping:
    repository: variable
    file-source: generated-config
  output_mapping:
    repository-commit: variable-commit

true_trigger: &true_trigger
  trigger: true

  
git_commit_env: &git_commit_env
  GIT_AUTHOR_EMAIL: "pcf-pipeline-bot@ebottnet.de"
  GIT_AUTHOR_NAME: "Platform Automation Bot"
  COMMIT_MESSAGE: 'Staged  Config Writer'

slack_start_param: &slack_start_param
  channel: ((slack.channel))
  text: |
    ((foundation)) Job $BUILD_JOB_NAME started with ID $BUILD_ID for 
    build $BUILD_NAME for team $BUILD_TEAM_NAME at
    $ATC_EXTERNAL_URL using pipeline  $BUILD_PIPELINE_NAME
    see $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
    for details
  icon_emoji: ":concourse-started:"

slack_succeeded_param: &slack_succeeded_param
  channel: ((slack.channel))
  text: |
    ((foundation)) Job $BUILD_JOB_NAME succeeded with ID $BUILD_ID for 
    build $BUILD_NAME for team $BUILD_TEAM_NAME at
    $ATC_EXTERNAL_URL using pipeline  $BUILD_PIPELINE_NAME    
    see $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
    for details
  icon_emoji: ":concourse-succeeded:"

slack_failed_param: &slack_failed_param
  channel: ((slack.channel))
  text: |
    ((foundation)) Job $BUILD_JOB_NAME failed with ID $BUILD_ID for 
    build $BUILD_NAME for team $BUILD_TEAM_NAME at
    $ATC_EXTERNAL_URL using pipeline  $BUILD_PIPELINE_NAME
    see $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
    for details
  icon_emoji: ":concourse-failed:"


resource_types:
- name: pivnet
  tags: ((tags))
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: additional-tasks
  icon: amazon-drive
  type: s3
  source:
    <<: *s3_env
    bucket: ((((foundation))/buckets_pivnet_tasks))
    regexp: additional-tasks-(.*).zip

- name: installation
  tags: ((tags))
  icon: amazon-drive
  type: s3
  source:
    <<: *s3_env
    bucket: ((buckets_installation))
    regexp: ((foundation))/installation-(.*).zip    

- name: platform-automation-pivnet
  tags: ((tags))
  icon: cloudfoundry
  type: pivnet
  source:
    api_token: ((((foundation))/pivnet-token))
    product_slug: platform-automation
    product_version: 4\.(.*)
    sort_by: semver

- name: platform-automation-tasks
  tags: ((tags))
  icon: amazon-drive
  type: s3
  source:
    <<: *s3_env
    bucket: ((((foundation))/buckets_pivnet_tasks))
    regexp: platform-automation-tasks-(.*).zip

- name: platform-automation-image
  tags: ((tags))
  icon: amazon-drive
  type: s3
  source:
    <<: *s3_env
    bucket: ((((foundation))/buckets_pivnet_image))
    regexp: platform-automation-image-(.*).tgz

- name: templates
  tags: ((tags))
  icon: github-circle
  type: git
  check_every: 10m  
  source: 
    uri: ((template.repo))
    private_key: ((((foundation))/template-deploy-key.private_key))
    branch: ((template.branch))

- name: opsman-product
  type: s3
  source:
    <<: *s3_env
    bucket: ((((foundation))/buckets_pivnet_products))
    regexp: \[ops-manager,(.*)\].*.yml
- name: variable
  tags: ((tags))
  icon: github-circle
  type: git
  check_every: 10m  
  source: 
    uri: ((variable-repo))
    private_key: ((((foundation))/variable-deploy-key.private_key))
    branch: master

- name: pipeline-lock
  icon: cloud-lock-outline
  type: pool
  check_every: 10m
  source:
    uri: ((variable-repo))
    branch: master
    pool: pas
    private_key: ((((foundation))/variable-deploy-key.private_key))
    retry_delay: 300s

- name: download-lock
  icon: cloud-lock-outline
  type: pool
  check_every: 10m
  source:
    uri: ((variable-repo))
    branch: master
    pool: download-lock
    private_key: ((((foundation))/variable-deploy-key.private_key))
    retry_delay: 300s

- name: azs-concourse
  tags: ((tags))
  icon: github-circle
  type: git
  check_every: 10m  
  source:  
    uri: https://github.com/bottkars/azs-concourse
    branch: master

interpolate-product-downloads: &interpolate-product-downloads
  image: platform-automation-image
  file: platform-automation-tasks/tasks/credhub-interpolate.yml
  params:
    <<: *credhub_env
    INTERPOLATION_PATHS: "download-product-configs/((tas_version))"
  input_mapping:
    files: templates
  output_mapping:
    interpolated-files: interpolated-product-downloads

interpolate-product-templates: &interpolate-product-templates
  image: platform-automation-image
  file: platform-automation-tasks/tasks/credhub-interpolate.yml
  params:
    <<: *credhub_env
    INTERPOLATION_PATHS: product-configs/((tas_version))
    SKIP_MISSING: true
  input_mapping:
    files: templates
  output_mapping:
    interpolated-files: interpolated-product-templates

jobs:
- name: test-azcli 
  plan:
  - get: azs-concourse
    tags: ((tags))
  - get: platform-automation-image
    tags: ((tags))
    params:
      unpack: true
  - task: test-azcli
    tags: ((tags))
    image: platform-automation-image
    file: azs-concourse/ci/tasks/test-task.yml

- name: run-azcli-get-vms
  plan:
  - get: variable
    tags: ((tags))
  - get: azs-concourse
    tags: ((tags))
  - get: platform-automation-image
    tags: ((tags))
    params:
      unpack: true
  - task: get-vms
    tags: ((tags))
    image: platform-automation-image
    file: azs-concourse/ci/tasks/get-vms.yml  
    input_mapping:
      config: variable
    params:
      <<: *azure_env

- name: clear-pipeline-lock
  plan:
  - get: pipeline-lock
    tags: ((tags)) 
  - put: pipeline-lock
    attempts: 5
    tags: ((tags))
    params: {release: pipeline-lock}      

- name: clear-download-lock
  plan:
  - get: download-lock
    tags: ((tags)) 
  - put: download-lock
    attempts: 5
    tags: ((tags))
    params: {release: download-lock}       
- name: reboot-control
  plan:
  - get: variable
    tags: ((tags))
  - get: azs-concourse
    tags: ((tags))
  - get: platform-automation-image
    tags: ((tags))
    params:
      unpack: true
  - task: reboot-rg
    tags: ((tags))
    image: platform-automation-image
    file: azs-concourse/ci/tasks/reboot-vms-rg.yml 
    input_mapping:
      config: variable
    params:
      <<: *azure_env
      RESOURCE_GROUP: control

- name: deploy-opsman-from-arm
  plan:
  - in_parallel:
    - get: variable
      tags: ((tags))
    - get: azs-concourse
      tags: ((tags))
    - get: platform-automation-image
      tags: ((tags))
      params:
        unpack: true
    - get: opsman-product
      tags: ((tags))
  - task: validate-template
    tags: ((tags))
    image: platform-automation-image
    file: azs-concourse/ci/tasks/validate-template.yml  
    input_mapping:
      config: variable
    params:
      <<: *azure_env
      TEMPLATE_URI: "https://raw.githubusercontent.com/bottkars/azure-pcf-opsman-powershell/testing/azuredeploy.json"
      PARAMETER_FILE: ((foundation))/config/parameters_opsman.json

      BOSHSTORAGEACCOUNT: ((boshstorageaccount))
      ADDITIONAL_PARAMETERS: "OpsManImageURI=https://opsmanagerimage.blob.local.azurestack.external/images/((opsman_image))"
  - task: deploy-opsman-template 
    tags: ((tags))
    image: platform-automation-image
    file: azs-concourse/ci/tasks/deploy-opsman-template.yml  
    input_mapping:
      config: variable
      image: opsman-product
    params:
      <<: *azure_env
      TEMPLATE_URI: "https://raw.githubusercontent.com/bottkars/azure-pcf-opsman-powershell/testing/azuredeploy.json"
      PARAMETER_FILE: ((foundation))/config/parameters_opsman.json

      BOSHSTORAGEACCOUNT: ((boshstorageaccount))
      OPSMAN_URL: ((opsman-url))
- name: manual-export-installation
  serial: true
  plan:
  - in_parallel:
      - get: platform-automation-image
        tags: ((tags))      
        params:
          unpack: true
      - get: platform-automation-tasks
        tags: ((tags))      
        params:
          unpack: true
      - get: templates
        tags: ((tags))      
      - get: variable
        tags: ((tags))      
  - task: export-installation
    tags: ((tags))      
    image: platform-automation-image
    file: platform-automation-tasks/tasks/export-installation.yml
    input_mapping:
      env: variable
    params:
      ENV_FILE: ((foundation))/env/env.yml
      INSTALLATION_FILE: installation-$timestamp.zip
  - put: installation
    tags: ((tags))      
    params:
      file: installation/installation*.zip
##
- name: set-opsman-banner
  serial: true
  plan:
  - in_parallel:
      - get: azs-concourse
      - get: platform-automation-image
        tags: ((tags))      
        params:
          unpack: true
#      - get: platform-automation-tasks
#        tags: ((tags))      
#        params:
#          unpack: true    
      - get: variable
        tags: ((tags))      
  - task: set-banner
    tags: ((tags))      
    image: platform-automation-image
    file: azs-concourse/ci/tasks/set-director-banner.yml
    input_mapping:
      env: variable
    params:
      ENV_FILE: ((foundation))/env/env.yml
      SSH_BANNER: ((director.ssh_banner))
      UI_BANNER: ((director.ui_banner))
##
#name: configure-wavefront-user
#  - task: configure-wavefront-user     
#    tags: ((tags))
#    image: platform-automation-image
#    file: additional-tasks/tasks/add-firehose-admin.yml
#    input_mapping:
#      env: variable
#    params:
#      FIREHOSE_FAMILY_NAME: wavefront
#      FIREHOSE_GIVEN_NAME: nozzle
#      FIREHOSE_USERNAME: wavefront-nozzle
#      FIREHOSE_PASSWORD: Thyph00n#
#      FIREHOSE_USER_EMAIL: email@na
#      UAA_ENDPOINT: ((pas-uaa-endpoint))
#      GROUP_NAMES: "doppler.firehose cloud_controller.admin_read_only"    
#      ENV_FILE: ((foundation))/env/env.yml
      
- name: delete-installation
  serial: true
  plan:
  - in_parallel:
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: variable
  - task: delete-installation
    image: platform-automation-image
    file: platform-automation-tasks/tasks/delete-installation.yml
    input_mapping:
      env: variable
    params:
    # VARS_FILES: vars/((foundation))/vars/opsman-vars.yml
     ENV_FILE: ((foundation))/env/env.yml
- name: update-om-certificates
  serial: true
  serial_groups: [ install ]
  plan:
  - in_parallel:
    - get: platform-automation-image
      tags: ((tags))
      params:
        unpack: true
    - get: additional-tasks
      tags: ((tags))
      params:
        unpack: true    
    - get: templates
      tags: ((tags))
    - get: variable
      tags: ((tags))
  - task: update om certficates
    tags: ((tags))
    image: platform-automation-image
    file: additional-tasks/tasks/update-ssl-certificate.yml
    input_mapping:
      env: variable
    params:
      ENV_FILE: ((foundation))/env/env.yml
      CERTIFICATE_PEM: ((pcf_domain_cert.certificate))
      KEY_PEM: ((pcf_domain_cert.private_key))

####
- name: delete-opsman-vm
  plan:
  - get: variable
    tags: ((tags))
  - get: azs-concourse
    tags: ((tags))
  - get: platform-automation-image
    tags: ((tags))
    params:
      unpack: true
  - task: delete-vm
    tags: ((tags))
    image: platform-automation-image
    file: azs-concourse/ci/tasks/delete-vm.yml  
    input_mapping:
      config: variable
    params:
      <<: *azure_env
      VM_NAME: ((ops_man_vmname))
      
- name: delete-orphan-azurevm-images
  plan:
  - get: variable
    tags: ((tags))
  - get: azs-concourse
    tags: ((tags))
  - get: platform-automation-image
    tags: ((tags))
    params:
      unpack: true
  - task: delete-images
    tags: ((tags))
    image: platform-automation-image
    file: azs-concourse/ci/tasks/delete-vm-images.yml  
    input_mapping:
      config: variable
    params:
      <<: *azure_env

- name: delete-unattached-azure-disks
  plan:
  - get: variable
    tags: ((tags))
  - get: azs-concourse
    tags: ((tags))
  - get: platform-automation-image
    tags: ((tags))
    params:
      unpack: true
  - task: delete-azure-disks
    tags: ((tags))
    image: platform-automation-image
    file: azs-concourse/ci/tasks/delete-unattached-disks.yml  
    input_mapping:
      config: variable
    params:
      <<: *azure_env


- name: query-unattached-azure-disks
  plan:
  - get: variable
    tags: ((tags))
  - get: azs-concourse
    tags: ((tags))
  - get: platform-automation-image
    tags: ((tags))
    params:
      unpack: true
  - task: query-azure-disks
    tags: ((tags))
    image: platform-automation-image
    file: azs-concourse/ci/tasks/query-unattached-disks.yml 
    input_mapping:
      config: variable
    params:
      <<: *azure_env


- name: query-unattached-azure-nics
  plan:
  - get: variable
    tags: ((tags))
  - get: azs-concourse
    tags: ((tags))
  - get: platform-automation-image
    tags: ((tags))
    params:
      unpack: true
  - task: query-azure-nics
    tags: ((tags))
    image: platform-automation-image
    file: azs-concourse/ci/tasks/query-unattached-nics.yml 
    input_mapping:
      config: variable
    params:
      <<: *azure_env


- name: delete-unattached-azure-nics
  plan:
  - get: variable
    tags: ((tags))
  - get: azs-concourse
    tags: ((tags))
  - get: platform-automation-image
    tags: ((tags))
    params:
      unpack: true
  - task: delete-azure-nics
    tags: ((tags))
    image: platform-automation-image
    file: azs-concourse/ci/tasks/delete-unattached-nics.yml 
    input_mapping:
      config: variable
    params:
      <<: *azure_env

- name: delete-pcf
  plan:
  - get: variable
    tags: ((tags))
  - get: azs-concourse
    tags: ((tags))
  - get: platform-automation-image
    tags: ((tags))
    params:
      unpack: true
  - task: delete-rg
    tags: ((tags))
    image: platform-automation-image
    file: azs-concourse/ci/tasks/delete-resourcegroup.yml  
    input_mapping:
      config: variable
    params:
      <<: *azure_env


- name: get-platform-automation
  plan: 
  - in_parallel:
    - get: platform-automation-pivnet
      tags: ((tags))
      trigger: true
  - in_parallel:
    - put: platform-automation-tasks
      tags: ((tags))
      params:
        file: platform-automation-pivnet/*tasks*.zip
    - put: platform-automation-image
      tags: ((tags))
      params:
        file: platform-automation-pivnet/*image*.tgz
- name: test-interpolate
  plan:
  - get: variable
    tags: ((tags))
  - get: templates
    tags: ((tags))
  - get: platform-automation-image
    tags: ((tags))
    params:
      unpack: true
  - get: platform-automation-tasks
    tags: ((tags))
    params:
      unpack: true
  - task: interpolate
    tags: ((tags))
    image: platform-automation-image
    file: platform-automation-tasks/tasks/test-interpolate.yml
    input_mapping:
      config: templates
      vars: variable
    params:
      CONFIG_FILE: product-configs/((tas_version))/p-event-alerts.yml
      VARS_FILES: vars/((foundation))/vars/p-event-alerts-vars.yml
      SKIP_MISSING: true    
#      VARS_FILES: vars/((foundation))/vars/pas_certs-vars.yml
      ENV_FILE: ((foundation))/env/env.yml

####
groups:




- name: service-jobs
  jobs:
  - clear-pipeline-lock
  - clear-download-lock
  - manual-export-installation
  - delete-installation
  - update-om-certificates
  - delete-orphan-azurevm-images
  - query-unattached-azure-disks
  - query-unattached-azure-nics
  - delete-unattached-azure-disks
  - delete-unattached-azure-nics
  - delete-opsman-vm
  - delete-pcf
  - test-azcli
  - run-azcli-get-vms
  - deploy-opsman-from-arm
  - get-platform-automation
  - reboot-control
  - set-opsman-banner
  - test-interpolate



