s3_env: &s3_env
  access_key_id: ((((foundation))/s3_access_key_id))
  endpoint:  ((((foundation))/s3_endpoint))
  region_name: ((((foundation))/s3_region_name))
  secret_access_key: ((((foundation))/s3_secret_access_key))


credhub_env: &credhub_env
  CREDHUB_CLIENT: ((((foundation))/credhub-client))
  CREDHUB_SECRET: ((((foundation))/credhub-secret))
  CREDHUB_SERVER: ((((foundation))/credhub-server))
  PREFIX: /concourse/main/((foundation))
  CREDHUB_CA_CERT: ((((foundation))/credhub-ca-cert.certificate))



resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
   

resources:
# triggers
#- name: daily-trigger
#  icon: calendar-clock
#  type: time
#  source:
#    interval: 24h


- name: one-time-trigger
  icon: calendar-clock
  type: time
  source:
    interval: 999999h

#- name: after-midnight
#  type: time
#  source:
#    start: 01:00 AM
#    stop: ((after_midnight_end))
#    interval: 24h
#    location: Europe/Berlin 

#- name: installation
#  icon: amazon-drive
#  type: s3
#  source:
#    <<: *s3_env
#    bucket: ((buckets.installation))
#    regexp: ((foundation))/installation-(.*).zip    
#- name: platform-automation-pivnet
#  type: pivnet
#  source:
#    api_token: ((((foundation))/pivnet-token))
#    product_slug: platform-automation
#    product_version: 4\.*\.(.*)
#    sort_by: semver


- name: dps-automation-image
  icon: amazon-drive
  type: s3
  source:
    <<: *s3_env
    bucket: ((buckets.pivnet_image))
    regexp: platform-automation-image-(.*).tgz


- name: azs-concourse
  tags: ((tags))
  icon: git
  type: git
  check_every: 10m  
  source:  
    uri: https://github.com/bottkars/azs-concourse.git
    branch: ((azs_concourse_branch))

## product resources
- name: networker
  type: s3
  icon: folder-move
  source:
    <<: *s3_env
    bucket: ((buckets.dps_products))
    regexp: networker/.*/NVE-(.*).ova


jobs:
#- name: get-platform-automation
#  plan:
#  - in_parallel:
#    - get: after-midnight
#      trigger: true
#    - get: platform-automation-pivnet
#      trigger: true
#    - put: dps-automation-image
#      params:
#        file: platform-automation-pivnet/*image*.tgz

- name: deploy-networker-ova
  plan:
  - in_parallel:
    - get: one-time-trigger
      trigger: true
    - get: networker
      tags: ((tags))
      params:
        unpack: true
      params:
        unpack: false
    - get: dps-automation-image
      params:
        unpack: true
      tags: ((tags))        
    - get: azs-concourse
      tags: ((tags))
  - task: deploy-ova
    tags: ((tags))
    image: dps-automation-image
    file: azs-concourse/ci/tasks/deploy-nve.yml
    input_mapping:
      azs-concourse: azs-concourse
      networker: networker
    params:
      GOVC_INSECURE: ((GOVC.INSECURE))
      GOVC_PASSWORD: ((GOVC.PASSWORD))
      GOVC_URL: ((GOVC.URL))
      GOVC_USERNAME: ((GOVC.USERNAME))
      GOVC_RESOURCE_POOL: ((GOVC.RESOURCE_POOL))
      GOVC_DATASTORE: ((GOVC.DATASTORE)) 
      GOVC_DATACENTER: ((GOVC.DATACENTER)) 
      GOVC_NETWORK: ((GOVC.NETWORK))
      NVE_NETWORK: ((NVE.NETWORK))
      NVE_ADDRESS: ((NVE.ADDRESS))
      NVE_GATEWAY: ((NVE.GATEWAY))
      NVE_NETMASK: ((NVE.NETMASK))
      NVE_FQDN: ((NVE.FQDN))
      NVE_VMNAME: ((NVE.VMNAME))
      NVE_DNS: ((NVE.DNS))       
- name: configure-nve
  plan:
  - in_parallel:
    - get: one-time-trigger
      trigger: true
    - get: dps-automation-image
      passed: [ deploy-networker-ova ]
      params:
        unpack: true
      tags: ((tags))        
    - get: azs-concourse
      tags: ((tags))
  - task: configure-nve
    tags: ((tags))
    image: dps-automation-image
    file: azs-concourse/ci/tasks/configure-nve.yml
    input_mapping:
      azs-concourse: azs-concourse
    params:
      GOVC_INSECURE: ((GOVC.INSECURE))
      GOVC_PASSWORD: ((GOVC.PASSWORD))
      GOVC_URL: ((GOVC.URL))
      GOVC_USERNAME: ((GOVC.USERNAME))
      GOVC_VM: ((NVE.VMNAME))     
      NVE_FQDN: ((NVE.FQDN))
      NVE_SETUP_PASSWORD: ((NVE.PASSWORD))  
      NVE_TIMEZONE: "((NVE.TIMEZONE))"
      NVE_ADMIN_PASSWORD_OS: ((NVE.PASSWORD)) 
      NVE_ROOT_PASSWORD_OS: ((NVE.PASSWORD)) 
      NVE_SNMP_STRING: ((NVE.SNMP_STRING))
      NVE_DATADOMAIN_HOST: ((NVE.DATADOMAIN_HOST))
      NVE_STORAGE_PATH: ((NVE.STORAGE_PATH))
      NVE_DDBOOST_USER: ((NVE.DDBOOST_USER))
      NVE_NEW_DDBOOST_USER: ((NVE.NEW_DDBOOST_USER))
      NVE_DDBOOST_USER_PWD: ((NVE.PASSWORD))
      NVE_DDBOOST_USER_PWD_CF: ((NVE.PASSWORD))
      NVE_DATADOMAIN_SYSADMIN: ((NVE.DATADOMAIN_SYSADMIN))
      NVE_DATADOMAIN_SYSADMIN_PWD: ((NVE.DATADOMAIN_SYSADMIN_PWD))
      NVE_TOMCAT_KEYSTORE_PASSWORD: ((NVE.PASSWORD)) 
      NVE_AUTHC_ADMIN_PASSWORD: ((NVE.PASSWORD))      
           
- name: delete-nve
  plan:
  - in_parallel:
    - get: dps-automation-image
      params:
        unpack: true
      tags: ((tags))
      passed: [ deploy-networker-ova ]              
    - get: azs-concourse
      tags: ((tags))
  - task: delete-nve
    tags: ((tags))
    image: dps-automation-image
    file: azs-concourse/ci/tasks/delete-nve.yml
    input_mapping:
      azs-concourse: azs-concourse
    params:
      GOVC_INSECURE: ((GOVC.INSECURE))
      GOVC_PASSWORD: ((GOVC.PASSWORD))
      GOVC_URL: ((GOVC.URL))
      GOVC_USERNAME: ((GOVC.USERNAME))
      GOVC_RESOURCE_POOL: ((GOVC.RESOURCE_POOL))
      GOVC_DATASTORE: ((GOVC.DATASTORE)) 
      GOVC_DATACENTER: ((GOVC.DATACENTER)) 
      GOVC_NETWORK: ((GOVC.NETWORK))
      NVE_VMNAME: ((NVE.VMNAME))
