---
platform: linux

inputs:
- name: platform-automation-tasks
- name: env # contains the env file with target OpsMan Information

params:
  ENV_FILE: env.yml
  PRODUCT_NAME: 
  # - Required
  # - Filepath of the env config YAML
  # - The path is relative to root of the `env` input

run:
  path: bash
  args:
  - "-c"
  - |
    set -eux
    om --env env/"${ENV_FILE}" apply-changes \
    --product-name ${PRODUCT_NAME} \
    --reattach  

