# code_snippet to create pks admin user
# 02.09.2019 @azurestack_guy
---
platform: linux

inputs:
- name: env # contains the env file with target OpsMan Information

params:
  ENV_FILE: env.yml
  # - Required
  # - Filepath of the env config YAML
  # - The path is relative to root of the `env` input
  KEY_FILE: opsman.key
  # conatins the opsman private key
  PKS_USERNAME: 
  PKS_PASSWORD: 
  PKS_API_ENDPOINT:
  PKS_USER_EMAIL: email@example.com


run:
  path: bash
  args:
  - "-c"
  - |
    cat /var/version && echo ""
    set -eu
    eval "$(om --env ./env/${ENV_FILE} \
        --skip-ssl-validation bosh-env --ssh-private-key ./env/${KEY_FILE})"
    deployments=$(bosh deployments --column=Name --json)
    PKS_DEPLOYMENT=$(echo $deployments | \
        jp.py "Tables[0].Rows[?contains(name,'pivotal-container-service')].name |[0]")
    PKS_DEPLOYMENT=$(echo "${PKS_DEPLOYMENT//\"}")
    ADMIN_CLIENT_SECRET=$(credhub get -n /opsmgr/${PKS_DEPLOYMENT}/pks_uaa_management_admin_client -k=value )
    echo "-->getting UAA Token"
    TOKEN=$(curl -k -s "https://${PKS_API_ENDPOINT}:8443/oauth/token" -X POST \
    -H "Accept: application/json" \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -d "client_id=admin&client_secret=${ADMIN_CLIENT_SECRET}&grant_type=client_credentials&token_format=opaque" \
     | awk -F\" '/access_token/{printf $4}')

    echo "-->Creating user ${PKS_USERNAME}"

    DATA=$(cat <<EOF
    {
        "userName" : "${PKS_USERNAME}",
        "name" : {
            "familyName" : "PKS",
            "givenName" : "ADMIN"
        },
        "emails" : [ {
            "value" : "${PKS_USER_EMAIL}",
            "primary" : true
        } ],
        "password" : "${PKS_PASSWORD}"
    }
    EOF
    )
    curl -k -s "https://${PKS_API_ENDPOINT}:8443/Users" -X POST \
    -H "Accept: application/json" \
    -H "Authorization: Bearer ${TOKEN}" \
    -H "Content-Type: application/json" \
    -d "${DATA}"

    USER_ID=$(curl -k -s "https://${PKS_API_ENDPOINT}:8443/Users?attributes=id%2CuserName&filter=userName+eq+%${PKS_USERNAME}" -X GET  \
    -H "Accept: application/json" \
    -H "Authorization: Bearer ${TOKEN}" | jp.py "resources[?userName=='$PKS_USERNAME'].id | [0]")
    
    USER_ID=$(echo "${USER_ID//\"}")

    GROUP_ID=$(curl -k -s "https://${PKS_API_ENDPOINT}:8443/Groups?scheme=openid&filter=displayName+eq+%pks.clusters.admin" -X GET \
    -H "Accept: application/json" \
    -H "Authorization: Bearer ${TOKEN}" | jp.py "resources[?displayName=='pks.clusters.admin'].id | [0]")

    GROUP_ID=$(echo "${GROUP_ID//\"}")

    DATA=$(cat <<EOF 
    {
        "origin" : "uaa",
        "type" : "USER",
        "value" : "${USER_ID}"
    }
    EOF
    )
    echo      
    echo "-->adding ${PKS_USERNAME} to ${GROUP_ID} (pks.clusters.admin)"

    curl -k  "https://${PKS_API_ENDPOINT}:8443/Groups/${GROUP_ID}/members" -X POST \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${TOKEN}" \
        -d "${DATA}"
