 code_snippet to create pks admin user
# 02.09.2019 @azurestack_guy
---
platform: linux

#inputs:
# - name: env # contains the env file with target OpsMan Information

params:

run:
  path: bash
  args:
  - "-c"
  - |
    set