---
networks-configuration:
 icmp_checks_enabled: false
 networks:
 - name: control-infrastructure-subnet
   subnets:
   - iaas_identifier: ((infrastructure-subnet))
     cidr: ((infrastructure_cidr))
     reserved_ip_ranges: ((infrastructure_range))
     dns: 168.63.129.16
     gateway: ((infrastructure_gateway))
 - name: control-plane-subnet
   subnets:
   - iaas_identifier: ((plane-subnet))
     cidr: ((plane_cidr))
     reserved_ip_ranges: ((plane_range))
     dns: 168.63.129.16
     gateway: ((plane_gateway))
network-assignment:
 network:
  name: control-infrastructure-subnet
 singleton_availability_zone:
  name: ((singleton_availability_zone))   
properties-configuration:
  security_configuration:
    trusted_certificates: ((fullchain))
    opsmanager_root_ca_trusted_certs: true
  director_configuration:
    max_threads: 8
    ntp_servers_string: ((ntp_servers_string))     
  iaas_configuration:
    subscription_id: ((subscription_id))
    tenant_id: ((tenant_id))
    client_id: ((client_id))
    client_secret: ((client_secret))
    resource_group_name: ((resource_group_name))
    cloud_storage_type: ((cloud_storage_type))
    storage_account_type: 
    deployed_cloud_storage_type: 
    deployments_storage_account_name: ((deployments_storage_account_name))
    bosh_storage_account_name: ((bosh_storage_account_name))
    default_security_group: ((default_security_group))
    ssh_public_key: ((ssh_public_key))
    ssh_private_key: ((ssh_private_key))
    availability_mode: ((availability_mode))
    environment: AzureStack
    azure_stack:
      domain: ((domain))
      authentication: AzureAD
      resource: ((ressource))
      endpoint_prefix: ((endpoint_prefix))
      ca_cert: ((ca_cert)) 
    additional_cloud_properties:
        azure_stack:
          domain: ((domain))
          authentication: ((authentication))
          resource: ((ressource))
          endpoint_prefix: ((endpoint_prefix))
          ca_cert: ((ca_cert))      
resource-configuration:
  director:
    instances: automatic
    persistent_disk:
      size_mb: "204800"
    instance_type:
      id: automatic

